/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as HistoireRouteImport } from './routes/histoire'
import { Route as ConformiteRouteImport } from './routes/conformite'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as CgvRouteImport } from './routes/cgv'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProduitSlugRouteImport } from './routes/produit.$slug'

const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoireRoute = HistoireRouteImport.update({
  id: '/histoire',
  path: '/histoire',
  getParentRoute: () => rootRouteImport,
} as any)
const ConformiteRoute = ConformiteRouteImport.update({
  id: '/conformite',
  path: '/conformite',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const CgvRoute = CgvRouteImport.update({
  id: '/cgv',
  path: '/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitSlugRoute = ProduitSlugRouteImport.update({
  id: '/produit/$slug',
  path: '/produit/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cgv': typeof CgvRoute
  '/confirmation': typeof ConfirmationRoute
  '/conformite': typeof ConformiteRoute
  '/histoire': typeof HistoireRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/panier': typeof PanierRoute
  '/produit/$slug': typeof ProduitSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cgv': typeof CgvRoute
  '/confirmation': typeof ConfirmationRoute
  '/conformite': typeof ConformiteRoute
  '/histoire': typeof HistoireRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/panier': typeof PanierRoute
  '/produit/$slug': typeof ProduitSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cgv': typeof CgvRoute
  '/confirmation': typeof ConfirmationRoute
  '/conformite': typeof ConformiteRoute
  '/histoire': typeof HistoireRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/panier': typeof PanierRoute
  '/produit/$slug': typeof ProduitSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cgv'
    | '/confirmation'
    | '/conformite'
    | '/histoire'
    | '/mentions-legales'
    | '/panier'
    | '/produit/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cgv'
    | '/confirmation'
    | '/conformite'
    | '/histoire'
    | '/mentions-legales'
    | '/panier'
    | '/produit/$slug'
  id:
    | '__root__'
    | '/'
    | '/cgv'
    | '/confirmation'
    | '/conformite'
    | '/histoire'
    | '/mentions-legales'
    | '/panier'
    | '/produit/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CgvRoute: typeof CgvRoute
  ConfirmationRoute: typeof ConfirmationRoute
  ConformiteRoute: typeof ConformiteRoute
  HistoireRoute: typeof HistoireRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PanierRoute: typeof PanierRoute
  ProduitSlugRoute: typeof ProduitSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/histoire': {
      id: '/histoire'
      path: '/histoire'
      fullPath: '/histoire'
      preLoaderRoute: typeof HistoireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conformite': {
      id: '/conformite'
      path: '/conformite'
      fullPath: '/conformite'
      preLoaderRoute: typeof ConformiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgv': {
      id: '/cgv'
      path: '/cgv'
      fullPath: '/cgv'
      preLoaderRoute: typeof CgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produit/$slug': {
      id: '/produit/$slug'
      path: '/produit/$slug'
      fullPath: '/produit/$slug'
      preLoaderRoute: typeof ProduitSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CgvRoute: CgvRoute,
  ConfirmationRoute: ConfirmationRoute,
  ConformiteRoute: ConformiteRoute,
  HistoireRoute: HistoireRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PanierRoute: PanierRoute,
  ProduitSlugRoute: ProduitSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
